# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmi2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
import sqlite3

class MyTypeError(Exception):
    def __str__(self):
        return "Error :)"


class Ui_BMI(object):
    def setupUi(self, BMI):
        BMI.setObjectName("BMI")
        BMI.resize(385, 402)

        self.conn=sqlite3.connect("bmi.db")
        self.cursor=self.conn.cursor()
        self.create_table()

        self.LineName = QtWidgets.QLineEdit(BMI)
        self.LineName.setGeometry(QtCore.QRect(30, 20, 113, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LineName.setFont(font)
        self.LineName.setText("")
        self.LineName.setObjectName("LineName")
        self.lineWeight = QtWidgets.QLineEdit(BMI)
        self.lineWeight.setGeometry(QtCore.QRect(30, 100, 113, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineWeight.setFont(font)
        self.lineWeight.setText("")
        self.lineWeight.setObjectName("lineWeight")
        self.lineHeight = QtWidgets.QLineEdit(BMI)
        self.lineHeight.setGeometry(QtCore.QRect(30, 180, 113, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineHeight.setFont(font)
        self.lineHeight.setText("")
        self.lineHeight.setObjectName("lineHeight")
        self.label = QtWidgets.QLabel(BMI)
        self.label.setGeometry(QtCore.QRect(190, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(BMI)
        self.label_2.setGeometry(QtCore.QRect(190, 110, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(BMI)
        self.label_3.setGeometry(QtCore.QRect(190, 190, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(BMI)
        self.pushButton.setGeometry(QtCore.QRect(20, 250, 321, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.my_calculate_bmi)
        self.label_4 = QtWidgets.QLabel(BMI)
        self.label_4.setGeometry(QtCore.QRect(20, 310, 161, 81))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ShowBmi = QtWidgets.QLineEdit(BMI)
        self.ShowBmi.setGeometry(QtCore.QRect(200, 320, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ShowBmi.setFont(font)
        self.ShowBmi.setMouseTracking(True)
        self.ShowBmi.setObjectName("ShowBmi")
        self.LineName.raise_()
        self.lineWeight.raise_()
        self.lineHeight.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.ShowBmi.raise_()
        self.label_2.raise_()

        self.retranslateUi(BMI)
        QtCore.QMetaObject.connectSlotsByName(BMI)

    def retranslateUi(self, BMI):
        _translate = QtCore.QCoreApplication.translate
        BMI.setWindowTitle(_translate("BMI", "Dialog"))
        self.label.setText(_translate("BMI", "Name"))
        self.label_2.setText(_translate("BMI", "Weight"))
        self.label_3.setText(_translate("BMI", "Height"))
        self.pushButton.setText(_translate("BMI", "Start"))
        self.label_4.setText(_translate("BMI", "This is ur BMI:"))

    def create_table(self):

        self.cursor.execute('''
        CREATE TABLE IF NOT EXISTS records 
            (
            id INTEGER PRIMARY KEY,               
            name TEXT NOT NULL,                
            weight REAL,   
            height REAL,                                    
            bmi REAL                
            )
    ''') 
        self.conn.commit()

    def my_calculate_bmi(self):
        try:
            name = self.LineName.text()
            weight=self.lineWeight.text()
            height=self.lineHeight.text()

            if not re.fullmatch(r"^[A-Z][a-z]+$",name):
                raise MyTypeError()

            if not re.fullmatch(r"^[1-9]\d*(\.\d+)?$",weight):
                raise MyTypeError()
            
            if not re.fullmatch(r"^[1-9]\d*$",height):
                raise MyTypeError()
            

            weight=float(weight)
            height=float(height)/100

            bmi= weight /(height**2)

            self.ShowBmi.setText(f"{bmi:.3f}")

            self.cursor.execute('''
        
            INSERT INTO records(name,weight,height,bmi) VALUES (?,?,?,?)
            ''',(name,weight,height,bmi))
            self.conn.commit()


        except MyTypeError as e:
            self.ShowBmi.setText(str(e))    

        except Exception:
            self.ShowBmi.setText("Error in Calculate")       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BMI = QtWidgets.QDialog()
    ui = Ui_BMI()
    ui.setupUi(BMI)
    BMI.show()
    sys.exit(app.exec_())
