# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmi4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import re


class MyTypeError(Exception):
    def __str__(self):
        return "Error :)"

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 682)

        self.conn=sqlite3.connect("bmi.db")
        self.cursor=self.conn.cursor()
        self.create_table()

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 330, 411, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.my_calculate_bmi)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 110, 291, 121))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(280, 210, 371, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 480, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.LineName = QtWidgets.QLineEdit(Dialog)
        self.LineName.setGeometry(QtCore.QRect(22, 40, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(25)   
        self.LineName.setFont(font)
        self.LineName.setObjectName("LineName")
        self.LineWeight = QtWidgets.QLineEdit(Dialog)
        self.LineWeight.setGeometry(QtCore.QRect(20, 130, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(25)   
        self.LineWeight.setFont(font)
        self.LineWeight.setObjectName("LineWeight")
        self.LineHeight = QtWidgets.QLineEdit(Dialog)
        self.LineHeight.setGeometry(QtCore.QRect(20, 230, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(25)   
        self.LineHeight.setFont(font)
        self.LineHeight.setObjectName("LineHeight")
        self.ShowBmi = QtWidgets.QLineEdit(Dialog)
        self.ShowBmi.setGeometry(QtCore.QRect(290, 480, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(25)   
        self.ShowBmi.setFont(font)
        self.ShowBmi.setObjectName("ShowBmi")
        self.statusLabel = QtWidgets.QLabel(Dialog)
        self.statusLabel.setGeometry(QtCore.QRect(30, 575, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Start"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_2.setText(_translate("Dialog", "Weight"))
        self.label_3.setText(_translate("Dialog", "Height"))
        self.label_4.setText(_translate("Dialog", "This is ur BMI:"))
        self.statusLabel.setText(_translate("Dialog", "There is no error for now :)"))

    
    def create_table(self):

        self.cursor.execute('''
        CREATE TABLE IF NOT EXISTS records 
            (
            id INTEGER PRIMARY KEY,               
            name TEXT NOT NULL,                
            weight REAL,   
            height REAL,                                    
            bmi REAL                
            )
    ''') 
        self.conn.commit()

    def my_calculate_bmi(self):
        try:
            name = self.LineName.text()
            weight=self.LineWeight.text()
            height=self.LineHeight.text()

            if not re.fullmatch(r"^[A-Z][a-z]+$",name):
                raise MyTypeError()

            if not re.fullmatch(r"^[1-9]\d*(\.\d+)?$",weight):
                raise MyTypeError()
            
            if not re.fullmatch(r"^[1-9]\d*$",height):
                raise MyTypeError()
            

            weight=float(weight)
            height=float(height)/100

            bmi= weight /(height**2)

            self.ShowBmi.setText(f"{bmi:.3f}")

            self.cursor.execute('''
            INSERT INTO records(name,weight,height,bmi) VALUES (?,?,?,?)
            ''',(name,weight,height,bmi))
            self.conn.commit()

            self.statusLabel.setText("✅ Saved to Database")
        except MyTypeError as e:
            self.ShowBmi.setText(str(e))
            self.statusLabel.setText("❌ invalid input")    

        except Exception as a:
            self.ShowBmi.setText("Error in Calculate")
            self.statusLabel.setText(f"❌ Error {a}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
